apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - name: https
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: ELASTIC_PASSWORD
            - name: xpack.security.enabled
              value: "true"
            # HTTP layer TLS configuration
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.certificate_authorities
              value: /usr/share/elasticsearch/config/certs/ca.crt
            - name: xpack.security.http.ssl.certificate
              value: /usr/share/elasticsearch/config/certs/es.crt
            - name: xpack.security.http.ssl.key
              value: /usr/share/elasticsearch/config/certs/es.key

          volumeMounts:
            - name: es-certs
              mountPath: /usr/share/elasticsearch/config/certs
              readOnly: true
            - name: es-data
              mountPath: /usr/share/elasticsearch/data

          resources:
{{ toYaml .Values.elasticsearch.resources | indent 12 }}

      volumes:
        - name: es-certs
          secret:
            secretName: es-certs

  # שים לב: זה צריך להיות בקו ישר מתחת ל-template (שני רווחים מההתחלה)
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage }}