apiVersion: v1
kind: Secret
metadata:
  name: es-certs
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  es.crt: {{ .Values.secrets.elasticsearch.crt | quote }}
  es.key: {{ .Values.secrets.elasticsearch.key | quote }}
  ca.crt: {{ .Values.secrets.caCrt | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-tls
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.secrets.kibana.crt | quote }}
  tls.key: {{ .Values.secrets.kibana.key | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pcap-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # אנחנו משתמשים באותה סיסמה גם לאפליקציה כדי שתתחבר ל-ES
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password | quote }}
  # במקרה של יוזר, כרגע אנחנו מניחים elastic כברירת מחדל, אבל אפשר להוסיף ל-values אם תרצה
  ELASTIC_USER: "elastic"